[package]
name = 'GMChat'
version = '1.0.0'

[addresses]
deployer = "0xfaf52ae1b48f945014ab1ba2798f85498995848cedfb0fbd167fada7ccb2d66e"
std = "0x1"
aptos_std = "0x1"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
AptosFramework = { local = "../aptos-framework" }

